language: android
before_install:
- openssl aes-256-cbc -K $encrypted_0b5eff37ea82_key -iv $encrypted_0b5eff37ea82_iv
  -in .env.enc -out .env -d
- nvm install 6
- node --version
install:
- npm install
android:
  components:
  - tools
  - build-tools-23.0.1
  - build-tools-25.0.3
  - platform-tools
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - intel-android-extra-license.+
script:
- cd android && ./gradlew assembleRelease --stacktrace --debug
